# Generated by Django 6.1 on 2026-08-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('Oracle DBA', 'Oracle DBA'), ('Oracle Developer', 'Oracle Developer'), ('PostgreSQL DBA', 'PostgreSQL DBA'), ('PostgreSQL Developer', 'PostgreSQL Developer')], max_length=50, null=True),
        ),
    ]
