# Generated by Django 6.1 on 2026-08-21 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 21, 9, 18, 23, 201294, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
