# Generated by Django 6.1 on 2026-08-21 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_studentcourse_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 21, 9, 23, 16, 185360, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
